/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sic115;

import contGeneral.ListaLibroDiario;
import contGeneral.libroDiario;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import otros.allFrames;

/**
 *
 * @author sic
 */
public class contabilidadGeneral extends javax.swing.JFrame {

    ListaLibroDiario list = new ListaLibroDiario();

    libroDiario libroactual = list.getActivoActual();
    ArrayList<libroDiario> ListaLibros = list.getActivosEinactivos();

    /**
     * Creates new form contabilidadGeneral
     */
    public contabilidadGeneral() {
        initComponents();
        allFrames.aplicarTema(this);
        new allFrames().CargarIcono(this);
        this.setLocationRelativeTo(null);
        this.setTitle("Contabilidad General");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIngTransacciones = new javax.swing.JButton();
        btnQueryTransacciones = new javax.swing.JButton();
        BtnGenerarEstados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculator.png"))); // NOI18N
        jLabel1.setText("Contabilidad General");

        btnIngTransacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book_accept.png"))); // NOI18N
        btnIngTransacciones.setText("Ingresar Transacciones");
        btnIngTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngTransaccionesActionPerformed(evt);
            }
        });

        btnQueryTransacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book_search.png"))); // NOI18N
        btnQueryTransacciones.setText("Consultar Transacciones");
        btnQueryTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryTransaccionesActionPerformed(evt);
            }
        });

        BtnGenerarEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/printer_accept.png"))); // NOI18N
        BtnGenerarEstados.setText("Generar Estados Financieros");
        BtnGenerarEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarEstadosActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/open_folder_info.png"))); // NOI18N
        jButton1.setText("Consulta de Estados de Subcuentas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(BtnGenerarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQueryTransacciones, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(btnIngTransacciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(btnIngTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnQueryTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnGenerarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngTransaccionesActionPerformed

        if (libroactual.getId() == null) {
            JOptionPane.showMessageDialog(this, "Debe abrir un nuevo periodo para comenzar a registrar");

            periodoNoAbierto periodoNuevoFrame = new periodoNoAbierto();
            periodoNuevoFrame.setVisible(true);

        } else {
            ingTransacciones transacc = new ingTransacciones();
            setVisible(false);
            transacc.setVisible(true);

            transacc.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {

                    setVisible(true);
                }

            });

        }

    }//GEN-LAST:event_btnIngTransaccionesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void BtnGenerarEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarEstadosActionPerformed

        boolean x;
        x = false;

        int comprueba = 0;

        for (libroDiario l : ListaLibros) {
            System.out.print(l.getFechafin());
            if (l.getCerrado()) {

                comprueba = comprueba + 1;

            }

        }
        if (comprueba == list.getActivosEinactivos().size()) {
            generarEstados generar = new generarEstados();
            setVisible(false);
            generar.setVisible(true);
            generar.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {

                    setVisible(true);
                }

            });
        } else {
            JOptionPane.showMessageDialog(this, "Cerrar los periodos contables");
        }


    }//GEN-LAST:event_BtnGenerarEstadosActionPerformed

    private void btnQueryTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryTransaccionesActionPerformed

        consultaTransaccion consultarT = new consultaTransaccion();
        setVisible(false);
        consultarT.setVisible(true);
        consultarT.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {

                setVisible(true);
            }

        });
    }//GEN-LAST:event_btnQueryTransaccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (list.getActivoActual() != null) {
            ConsultaCuenta consultarT = new ConsultaCuenta();
            setVisible(false);
            consultarT.setVisible(true);
            consultarT.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {

                    setVisible(true);
                }

            });

        } else {

            JOptionPane.showMessageDialog(this, "Periodo a consultar debe estar abierto", "Periodos cerrados", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contabilidadGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contabilidadGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contabilidadGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contabilidadGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contabilidadGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGenerarEstados;
    private javax.swing.JButton btnIngTransacciones;
    private javax.swing.JButton btnQueryTransacciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
