/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sic115;

import MateriaPrima.OpCierreMP;
import MateriaPrima.productoTerminado;
import contGeneral.ListaLibroDiario;
import contGeneral.libroDiario;
import contGeneral.operacionesCierre;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import otros.allFrames;

/**
 *
 * @author sic
 */
public class finalIniPeriodo extends javax.swing.JFrame {

    ListaLibroDiario list = new ListaLibroDiario();
    libroDiario libroactual = list.getActivoActual();
    ArrayList<libroDiario> ListaLibros = list.getActivosEinactivos();
    operacionesCierre cierre = new operacionesCierre();
    OpCierreMP cierremp = new OpCierreMP();
    productoTerminado productoT= new productoTerminado();

    /**
     * Creates new form finalIniPeriodo
     */
    public finalIniPeriodo() {
        initComponents();
        allFrames.aplicarTema(this);
        new allFrames().CargarIcono(this);
        llenarCombo();
        this.setLocationRelativeTo(null);

        this.setTitle("Periodo Contable");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        comboActivos = new javax.swing.JComboBox();
        Cerrar = new javax.swing.JButton();
        crear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendar.png"))); // NOI18N
        label.setText("Periodo Contable");

        comboActivos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Cerrar.setText("Cerrar Periodo Contable");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        crear.setText("Crear Periodo Contable");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cerrar)
                                .addGap(18, 18, 18)
                                .addComponent(crear)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label)
                .addGap(32, 32, 32)
                .addComponent(comboActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar)
                    .addComponent(crear))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        int aprobacion;
        aprobacion = 1;
        libroDiario libroAfectado = (libroDiario) this.comboActivos.getSelectedItem();
        if (libroAfectado.getCerrado()) {
            JOptionPane.showMessageDialog(this, "Este periodo ya esta cerrado");
        } else {
            aprobacion = JOptionPane.showConfirmDialog(this, "Una vez cerrado, el periodo contable no se podra abrir ¿Esta seguro?");

        }
        if (aprobacion == 0) {
            try {

                cierre.crearcopia(libroAfectado.getId());
                productoT.baguette();
                productoT.galletaMaria();
                productoT.productoTerminadoVacio();
                cierremp.copiaKardex();
                cierremp.recuperarMPAzucar();
                cierremp.recuperarMPHarina();
                cierremp.recuperarMPHuevos();
                cierremp.recuperarMPLevadura();
                cierremp.recuperarMantecaMP();
                cierremp.recuperarMpsal();
                
                
                cierremp.vaciarkardex();
                

                this.list.cerrarLibro();

                JOptionPane.showMessageDialog(this, "Periodo cerrado con exito");
                this.llenarCombo();
                this.comboActivos.repaint();

            } catch (SQLException ex) {
                Logger.getLogger(finalIniPeriodo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_CerrarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        if (list.getActivoActual().getCerrado() == null) {

            periodoNoAbierto nuevo = new periodoNoAbierto();
            nuevo.setVisible(true);
            nuevo.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    llenarCombo();
                    //prueba 

                }

            });
        } else {

            JOptionPane.showMessageDialog(this, "Debe cerrar todos los periodos contables para abrir nuevo periodo");
        }

    }//GEN-LAST:event_crearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalIniPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalIniPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalIniPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalIniPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalIniPeriodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JComboBox comboActivos;
    private javax.swing.JButton crear;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

    private void llenarCombo() {

        DefaultComboBoxModel value;
        this.comboActivos.removeAllItems();

        comboActivos.removeAllItems();
        value = new DefaultComboBoxModel();
        comboActivos.setModel(value);
        this.ListaLibros.clear();
        ListaLibros = list.getActivosEinactivos();
        for (libroDiario aux : ListaLibros) {
            libroDiario a = aux;
            value.addElement(a);

        }
        this.comboActivos.repaint();
    }

}
